const dotenv = require('dotenv');
dotenv.config();
const { APP_PORT = 3000 } = process.env;
const { 
  HOST,USER,PASSWORD,DB,PORT,SECRET_JWT_KEY,
  FRONTEND_URL,BACKEND_URL,EMAIL_PASSWORD,EMAIL_USER,
  OAUTH2_CLIENT_ID, OAUTH2_CLIENT_SECRET,CALL_BACK_URL
}= process.env;

module.exports = {
  APP_PORT,
  HOST,
  USER,
  PASSWORD,
  DB,
  PORT,
  SALT_ROUNDS:10,
  SECRET_JWT_KEY,
  FRONTEND_URL,
  BACKEND_URL,
  EMAIL_PASSWORD,
  EMAIL_USER,
  OAUTH2_CLIENT_SECRET,
  OAUTH2_CLIENT_ID,CALL_BACK_URL
};